language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=ecl

matrix:
  allow_failures:
    - env: LISP=ecl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

script:
    # It's an interactive application so we can't do anything more than just load it
  - cl -e '(ql:quickload :dithcord-tui)'

